// Code generated by scripts/gen-opencode-plugin-digests.sh; DO NOT EDIT.

package opencoderuntimeplugins

// releasedPluginDigests maps each managed or retired OpenCode plugin name to
// the SHA-256 of every byte sequence a Gentle AI release shipped for it.
var releasedPluginDigests = map[string][]string{
	"background-agents.ts": {
		"61e4bd24cb425badf5401d3c2502da4c03d89446b122b3905921de559f7dd876", // plugins/ v1.7.0 to v1.7.8
		"e04ef03e6dae78e99ee59ea9faf2daa00ff2f6408a9d61ab96b4a4cfd5c9554f", // plugins/ v1.7.9 to v1.7.18
		"4c75e40b3bfd1eb7310612b6016cab88dc35662b3ad30ccc73eaacf53e2b6079", // plugins/ v1.7.19 to v1.7.20
		"3fe969ddfbbcb1c423126e7ccdfa95cad5990fd08b489da8323e20e1d87d3ac9", // plugins/ v1.7.21 to v1.12.2
		"b0bd3354e6d33fc35895e6e43003539812c1b001e734ef298e62ffb63eb23d34", // plugins/ v1.12.3 to v1.18.1
		"f6a7568d0b8f0a4a0a1eb52cbd15e644ff342ca84172299c3cb6d51d4618cd5c", // plugins/ v1.18.2 to v1.27.5
		"ce0ed98eb8513e4d93dbb492f131906197227678ed8d314f38a32ba97cfe5139", // plugins/ v1.28.0
		"5b2ad64ea95d47f34d1c572951c670f125a1807cd7a9c125146307892fbbdcb8", // plugins/ v1.28.1 to v1.33.1
		"2cebf28b9b5f3d4bd56b980abf33278178520a9b159b9075bcdd933d3f2893a5", // plugins/ v1.33.2 to v1.37.2
	},
	"model-variants.ts": {
		"fdcbf9c6e4c398216c32394abf4c1ee2f9ed17eb96b1238c226bf5dd6a08416f", // plugins/ v1.29.0 to v1.39.4
		"47bad2b6a0ebc13cb921174b8b2d61628767b312edd2373a426b6979e5df170d", // plugins/ v1.40.1 to v4.0.0
		"6c894d141b97b67f2689b41afc79579ce3be2f3aa57aa2de9586645fbf0b18f4", // plugins-v2/ v3.3.0 to v4.0.0
	},
	"opencode-review-transport.ts": {
		"fa4c1674d8897371341088548e1c4be9098be03f737e97878d008327f6b38e66", // plugins/ v2.4.0-rc.8
		"05e60cfdce94b017c569fa1752c02938cfd0aebedd4a6d86d2430ed2a4808653", // plugins/ v2.4.0
		"aa2f0beffddc3496a7e5ddd9eb26d963be7efab31123fd65e7126d478028f222", // plugins/ v2.5.0-rc.1 to v3.7.0
		"886f5c89a6da4ae1b378aed39cbc7f90b0e4dc5c92350660db015287fb3c2445", // plugins-v2/ v3.3.0 to v3.7.0
		"e52edacb8868d227cb5ec74505fa60dc555d120ec7b5c64ceaf0291176856e94", // plugins-v2/ v4.0.0
		"3e58dde99d5a8ecf4d1a8377a24c86cb90ef99015815ab93f1775bdbc5766268", // plugins/ v4.0.0
		"0f2a91a3579f65d5b04a94c0833103d2b9c37a7869c3880eed34d8bbbdc0e3c5", // plugins-v2/ unreleased
	},
	"review-result-artifacts.ts": {
		"5f22438ddf29e1c0f0aad68a48f8feb4c188a01e8d6853d062a09c60a7e39936", // plugins/ v2.1.7
		"aadd84d25b4343df6847202a50f3d5100f5a34b24eb86d18e4a2be17973faf25", // plugins/ v2.1.8 to v2.1.11
		"c52238f15d06e1050e6206b86373a4688da12df19f2c619aae781fdf88433205", // plugins/ v2.2.0-rc.1
		"00262e19f81dc77e10485194793292ed7dcab2ff69168e80071fe59abff11482", // plugins/ v2.2.0
		"7bd3405b6ee867767bbeb31674703bde93fe7cb0b0fede8bc02c8813160d365d", // plugins/ v2.2.1 to v2.2.3-rc.3
		"40ace33edcdafff32fa5fb3d7dcea4a44c8ea50244fcefa1221f3992cb6ca6ea", // plugins/ v2.2.3-rc.4 to v2.2.4
		"ba3e7c66fd72758c7edc6785de9b0b3f88ca5e7d135c1b7aba738cd573628f11", // plugins/ v2.3.0-rc.1
		"8f3142439b2dd39ec9615f5d8f99d984b57453c596621f1ccc5afdddcbebd60e", // plugins/ v2.3.0-rc.2 to v2.3.0
		"06969058586a3ac26f59ccc8be8dc236db3815ec4b6b4ca62f7ca1e0b9270c87", // plugins/ v2.4.0-rc.1 to v2.4.0-rc.6
		"5ab48f728e7a8d1799dff1624e5842ab76077ca0aa346b04a7f7ac1fcee0f27f", // plugins/ v2.4.0-rc.7
	},
	"sdd-task-result-artifacts.ts": {
		"bfd291ff60c7d186d3e727327a9cc038a8ac4275128bcb8b406cb322858eb6f6", // plugins/ v2.4.0-rc.8 to v2.4.0
		"a571b08f05c6f0d3726fbbd0144b387d2b139c4a701f398d7c7d2044878dd3d5", // plugins/ v2.5.0-rc.1 to v2.5.0-rc.3
		"0c514e085be33de5871da15bd2b021aea286676c2a4b723c31ba02b8acd8833d", // plugins/ v2.5.0 to v2.6.0
		"b8f1cdcfe38df960d37d8700eb6a9875335302761bfca1d0d10df02b4c18b7d4", // plugins/ v2.7.0-rc.1 to v2.7.0
		"9440325b6ea325804f4972a993cbb457b7babe0085010a47e16c00763afb9c5f", // plugins/ v2.8.0 to v2.8.1
		"e497b37070f5178fcab110bd964b7fd0af6e299c467eb630093f9c4d9ca7e404", // plugins/ v2.8.2 to v3.7.0
		"2c49d774b21edaf7bd6ffb9d3447d9dd54828dce6dd846fcc49274173bebd3ca", // plugins-v2/ v3.3.0 to v3.7.0
	},
	"skill-registry.ts": {
		"b24f83e90d455807dbd122f12a953952e7ff6550e3a0d733030c22843f0ce148", // plugins/ v1.39.1 to v2.4.0-rc.7
		"d402d2414b3c9ec5b31cad6f85787d152037e76148c3cea18fd443c1d7f5eab4", // plugins/ v2.4.0-rc.8
		"af143abb8250087431110739af3e6ae7b16c963f200968b777e1f38b3e58d8ff", // plugins/ v2.4.0
		"12dcf0eb388ebbb000d8ac318b906a3ab3f7880049fcc0ceed2012143271c4cd", // plugins/ v2.5.0-rc.1 to v3.6.0
		"c2b4382c014c2c15d4b18c70df8d65c272e557d2639e2b2f1ad8d9236142dc48", // plugins-v2/ v3.3.0 to v4.0.0
		"eaae11a2e1bcbdfaeeb030a40de46e15a8c098bfef3018226fc8e05327e86cdf", // plugins/ v3.6.1 to v4.0.0
	},
}
