#!/usr/bin/env bash
# Generate the SHA-256 registry of every managed OpenCode plugin byte sequence
# Gentle AI has shipped, so an upgrade can recognize its own earlier plugins as
# owned (issue #5185) while still preserving bytes no release ever wrote.
#
# Sources: the plugin assets at every local `v*` release tag plus the assets in
# the current working tree (not yet released). Fetch tags first:
#
#   git fetch --tags
#   go generate ./internal/components/opencoderuntimeplugins/
#
# TestReleasedPluginDigestsCoverEmbeddedAssets fails when an embedded asset
# changes without regenerating, so the registry only ever grows. The generator
# refuses an incomplete local tag set instead of silently dropping history:
# known anchor tags must exist, and every released digest in the committed
# registry must be regenerated. Unreleased digests track the working tree and
# may change between releases.
set -euo pipefail

root=$(git rev-parse --show-toplevel)
names='background-agents.ts model-variants.ts opencode-review-transport.ts review-result-artifacts.ts sdd-task-result-artifacts.ts skill-registry.ts'
anchors='v1.7.19 v4.0.0'
registry_path=internal/components/opencoderuntimeplugins/released_digests.go
dirs='internal/assets/opencode/plugins internal/assets/opencode/plugins-v2'

if command -v sha256sum >/dev/null; then
	sha256() { sha256sum | cut -d' ' -f1; }
else
	sha256() { shasum -a 256 | cut -d' ' -f1; }
fi

tags=$(git -C "$root" -c versionsort.suffix=- tag -l 'v*' --sort=v:refname)
if [ -z "$tags" ]; then
	echo "no v* release tags found; run git fetch --tags" >&2
	exit 1
fi
for anchor in $anchors; do
	if ! git -C "$root" rev-parse -q --verify "refs/tags/$anchor^{commit}" >/dev/null; then
		echo "release tag $anchor missing; the local tag set is incomplete; run git fetch --tags" >&2
		exit 1
	fi
done

# Released bytes are git blobs: the working tree is LF-normalized by
# .gitattributes, so blob bytes are the bytes every release embedded. Digest
# each distinct blob once.
tagged=$(
	for tag in $tags; do
		# shellcheck disable=SC2086
		git -C "$root" ls-tree -r "$tag" -- $dirs | while read -r _ _ blob path; do
			echo "${path##*/} ${path%/*} $tag $blob"
		done
	done
)
blob_digests=$(echo "$tagged" | cut -d' ' -f4 | sort -u | while read -r blob; do
	[ -n "$blob" ] || continue
	sum=$(git -C "$root" cat-file blob "$blob" | sha256) || {
		echo "cannot read release blob $blob" >&2
		exit 1
	}
	echo "$blob $sum"
done)

# rows: <name> <asset dir> <source> <digest>, in release order. Unreleased
# assets are digested from the working-tree bytes go:embed reads, staged or not.
rows=$(
	awk 'NR == FNR { digest[$1] = $2; next } NF { print $1, $2, $3, digest[$4] }' \
		<(echo "$blob_digests") <(echo "$tagged")
	for dir in $dirs; do
		for name in $names; do
			file="$root/$dir/$name"
			[ -e "$file" ] || [ -L "$file" ] || continue
			sum=$(sha256 <"$file") || {
				echo "cannot read plugin asset $dir/$name" >&2
				exit 1
			}
			echo "$name $dir unreleased $sum"
		done
	done
)
if echo "$rows" | awk 'NF && (length($4) != 64 || $4 ~ /[^0-9a-f]/) { bad = 1 } END { exit !bad }'; then
	echo "invalid plugin digest rows:" >&2
	echo "$rows" | awk 'NF && (length($4) != 64 || $4 ~ /[^0-9a-f]/)' >&2
	exit 1
fi

registry=$(
	echo '// Code generated by scripts/gen-opencode-plugin-digests.sh; DO NOT EDIT.'
	echo
	echo 'package opencoderuntimeplugins'
	echo
	echo '// releasedPluginDigests maps each managed or retired OpenCode plugin name to'
	echo '// the SHA-256 of every byte sequence a Gentle AI release shipped for it.'
	echo 'var releasedPluginDigests = map[string][]string{'
	awk -v names="$names" '
		{
			split($2, parts, "/"); dir = parts[length(parts)] "/"
			key = $1 SUBSEP $4
			if (!(key in seen)) { seen[key] = 1; order[$1] = order[$1] " " $4 }
			if (index(dirsOf[key] " ", " " dir " ") == 0) dirsOf[key] = dirsOf[key] " " dir
			if ($3 != "unreleased") { if (!(key in first)) first[key] = $3; last[key] = $3 }
		}
		END {
			n = split(names, list, " ")
			for (i = 1; i <= n; i++) {
				name = list[i]
				if (order[name] == "") continue
				printf "\t\"%s\": {\n", name
				m = split(order[name], sums, " ")
				for (j = 1; j <= m; j++) {
					key = name SUBSEP sums[j]
					span = "unreleased"
					if (key in first) span = first[key] (first[key] == last[key] ? "" : " to " last[key])
					printf "\t\t\"%s\", //%s %s\n", sums[j], dirsOf[key], span
				}
				printf "\t},\n"
			}
		}
	' <(echo "$rows")
	echo '}'
)

# pairs lists "<name> <digest>" for every registry entry; with "released" it
# skips unreleased digests, which a later edit of the same asset may replace.
pairs() {
	awk -F'"' -v only="${1:-}" '
		/^\t"/ { name = $2 }
		/^\t\t"/ && !(only == "released" && $0 ~ /unreleased$/) { print name, $2 }
	' | sort -u
}

committed=$(git -C "$root" show "HEAD:$registry_path" 2>/dev/null || true)
dropped=$(comm -23 <(echo "$committed" | pairs released) <(echo "$registry" | pairs))
if [ -n "$dropped" ]; then
	echo "regenerated registry drops $(echo "$dropped" | wc -l | tr -d ' ') committed digest(s); the local tag set is incomplete; run git fetch --tags:" >&2
	echo "$dropped" >&2
	exit 1
fi

# Write to the optional output path, otherwise stdout.
if [ $# -gt 0 ]; then
	exec >"$1"
fi
printf '%s\n' "$registry"
