// Code generated by scripts/gen-sdd-agent-digests; DO NOT EDIT.

package legacyassets

// The registry was generated from these release tags, closed at v4.0.0.
// The generator refuses a local tag set missing any of them.
// tags: v0.1.1 v1.0.0 v1.0.1 v1.0.2 v1.0.3 v1.0.4 v1.0.5 v1.0.6 v1.0.7 v1.0.8
// tags: v1.0.9 v1.1.0 v1.2.0 v1.2.1 v1.3.0 v1.3.1 v1.3.2 v1.3.3 v1.3.4 v1.4.0
// tags: v1.4.1 v1.4.2 v1.4.3 v1.4.4 v1.4.5 v1.4.6-beta.1 v1.4.6 v1.4.7 v1.4.8 v1.4.9
// tags: v1.4.10 v1.4.11 v1.4.12 v1.4.13 v1.4.14 v1.5.0 v1.5.1 v1.5.2 v1.5.3 v1.5.4
// tags: v1.5.5 v1.6.0 v1.6.1 v1.6.2 v1.6.3 v1.7.0 v1.7.1 v1.7.2 v1.7.3 v1.7.4
// tags: v1.7.5 v1.7.6 v1.7.7 v1.7.8 v1.7.9 v1.7.10 v1.7.11 v1.7.12 v1.7.13 v1.7.14
// tags: v1.7.15 v1.7.16 v1.7.17 v1.7.18 v1.7.19 v1.7.20 v1.7.21 v1.7.22 v1.7.23 v1.7.24
// tags: v1.8.0-beta.1 v1.8.0 v1.8.1 v1.8.2 v1.8.3 v1.8.4 v1.8.5 v1.8.6 v1.8.7 v1.8.8
// tags: v1.8.9 v1.8.10 v1.8.11 v1.8.12 v1.8.13 v1.8.14 v1.9.0 v1.9.1 v1.9.2 v1.9.3
// tags: v1.10.0 v1.10.1 v1.10.2 v1.10.3 v1.10.4 v1.11.0 v1.11.1 v1.11.2 v1.11.3 v1.11.4
// tags: v1.11.5 v1.11.6 v1.12.0 v1.12.1 v1.12.2 v1.12.3 v1.13.0 v1.13.1 v1.13.2 v1.13.3
// tags: v1.13.4 v1.14.0 v1.14.1 v1.14.2 v1.14.3 v1.14.4 v1.15.0 v1.15.1 v1.15.2 v1.15.3
// tags: v1.15.4 v1.15.5 v1.15.6 v1.15.7 v1.15.8 v1.15.9 v1.15.10 v1.15.11 v1.15.12 v1.15.13
// tags: v1.15.14 v1.16.0 v1.16.1 v1.17.0 v1.18.0 v1.18.1 v1.18.2 v1.18.3 v1.18.4 v1.19.0
// tags: v1.19.1 v1.20.0 v1.20.1 v1.21.0 v1.22.0 v1.23.0 v1.24.0 v1.24.1 v1.24.2 v1.24.3
// tags: v1.25.0 v1.25.1 v1.25.2 v1.25.3 v1.25.4 v1.25.5 v1.25.6 v1.26.0 v1.26.1 v1.26.2
// tags: v1.26.3 v1.26.4 v1.26.5 v1.26.6 v1.27.0 v1.27.1 v1.27.2 v1.27.3 v1.27.4 v1.27.5
// tags: v1.28.0 v1.28.1 v1.28.2 v1.28.3 v1.29.0 v1.29.1 v1.30.0 v1.30.1 v1.30.2 v1.30.3
// tags: v1.30.4 v1.30.5 v1.30.6 v1.30.7 v1.30.8 v1.30.9 v1.30.10 v1.31.0 v1.32.0 v1.33.0
// tags: v1.33.1 v1.33.2 v1.34.0 v1.34.1 v1.34.2 v1.35.0 v1.36.0 v1.36.1 v1.36.2 v1.36.3
// tags: v1.36.4 v1.36.5 v1.36.6 v1.36.7 v1.36.8 v1.37.0 v1.37.1 v1.37.2 v1.38.0 v1.39.0
// tags: v1.39.1 v1.39.2 v1.39.3 v1.39.4 v1.40.1 v1.40.2 v1.41.0 v1.42.0 v1.43.0 v1.43.1
// tags: v1.43.2 v1.43.3 v1.43.4 v1.44.0 v1.44.1 v1.44.2 v1.44.3 v1.45.0 v1.46.0 v1.47.0
// tags: v1.48.0 v1.49.0 v2.0.0 v2.0.1 v2.0.2 v2.1.0 v2.1.1 v2.1.2 v2.1.3 v2.1.4
// tags: v2.1.5 v2.1.6 v2.1.7 v2.1.8 v2.1.9 v2.1.10 v2.1.11 v2.2.0-rc.1 v2.2.0 v2.2.1
// tags: v2.2.2 v2.2.3-rc.1 v2.2.3-rc.2 v2.2.3-rc.3 v2.2.3-rc.4 v2.2.3 v2.2.4 v2.3.0-rc.1 v2.3.0-rc.2 v2.3.0-rc.3
// tags: v2.3.0 v2.4.0-rc.1 v2.4.0-rc.3 v2.4.0-rc.4 v2.4.0-rc.6 v2.4.0-rc.7 v2.4.0-rc.8 v2.4.0 v2.5.0-rc.1 v2.5.0-rc.2
// tags: v2.5.0-rc.3 v2.5.0 v2.6.0 v2.7.0-rc.1 v2.7.0 v2.8.0 v2.8.1 v2.8.2 v2.9.0 v2.9.1
// tags: v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1
// tags: v3.7.0 v4.0.0

// releasedOpenCodeSDDDescriptions maps a retired SDD agent to every
// description a release wrote for it in OpenCode settings.
var releasedOpenCodeSDDDescriptions = map[string][]string{
	"sdd-apply": {
		"Implement code changes from task definitions", // v1.5.0 to v3.7.0
	},
	"sdd-archive": {
		"Archive completed change artifacts", // v1.5.0 to v3.7.0
	},
	"sdd-design": {
		"Create technical design from proposals", // v1.5.0 to v3.7.0
	},
	"sdd-explore": {
		"Investigate codebase and think through ideas", // v1.5.0 to v3.7.0
	},
	"sdd-init": {
		"Bootstrap SDD context and project configuration", // v1.5.0 to v3.7.0
	},
	"sdd-onboard": {
		"Guide user through a complete SDD cycle using their real codebase", // v1.15.14 to v3.7.0
	},
	"sdd-orchestrator": {
		"Gentleman personality + SDD delegate-only orchestrator",                                          // v1.5.0 to v1.7.19
		"Agent Teams Orchestrator - coordinates sub-agents, never does work inline",                       // v1.5.0 to v1.21.0
		"Agent Teams Orchestrator ({{PROFILE}} profile) - coordinates sub-agents, never does work inline", // v1.17.0 to v1.21.0
		"SDD Orchestrator - coordinates sub-agents, never does work inline",                               // v1.22.0 to v1.24.3
		"SDD Orchestrator ({{PROFILE}} profile) - coordinates sub-agents, never does work inline",         // v1.22.0 to v3.7.0
	},
	"sdd-propose": {
		"Create change proposals from explorations", // v1.5.0 to v3.7.0
	},
	"sdd-research": {
		"Collect source-backed evidence for selected SDD research", // v2.5.0-rc.1 to v3.7.0
		"Collect auditable external evidence",                      // v2.5.0-rc.1 to v3.7.0
	},
	"sdd-spec": {
		"Write detailed specifications from proposals", // v1.5.0 to v3.7.0
	},
	"sdd-tasks": {
		"Break down specs and designs into implementation tasks", // v1.5.0 to v3.7.0
	},
	"sdd-verify": {
		"Validate implementation against specs", // v1.5.0 to v3.7.0
	},
}

// releasedOpenCodeSDDPrompts maps a retired SDD agent to the normalized
// digest of every inline prompt a release wrote for it.
var releasedOpenCodeSDDPrompts = map[string][]string{
	"sdd-apply": {
		"6d13171e7269efaaec309f79e5639db91980d77e1dd2974926dfe8b3fa1a7946", // v1.5.0 to v1.5.4
		"e799a1d9d0eff38cf5c92898c30a68293760920fa286e6fb35e08ffc5e214011", // v1.5.5 to v1.8.0
		"46937f014b68720ba96413e40a9a4691f6c1cf31154fb63fd2442d25b84c81ed", // v1.8.1 to v1.37.2
		"c8dd27c50c73f82c4d96552f8e497e22969100b34aaf1161622c0c8148a437c5", // v1.38.0 to v3.7.0
	},
	"sdd-archive": {
		"bd95fda3743582fee013d1e763e31fbfce86afd866dd17037e80036e7212abed", // v1.5.0 to v1.5.4
		"01e1122a923685858b42458c3c07563f824bc5b55718589d3568a0eb9c03620a", // v1.5.5 to v1.8.0
		"a8a4d573de8d7fe61caabd8e5d419d23ec582c5bb961de819e0515a1b4a722a5", // v1.8.1 to v1.37.2
		"c5533c9afa4b01d225b59c16f6137cca37eceff3da85c81406457cd9708686d0", // v1.38.0 to v3.7.0
	},
	"sdd-design": {
		"d11b690c756742e043db412a0e4a8841d50ae2c7ac1a25197a638e6c119da7fc", // v1.5.0 to v1.5.4
		"0d657fb05244dea5622a742cd58e055f9215e4e887d05f166683d0eaa476d7f3", // v1.5.5 to v1.8.0
		"d8ee33c9d3adfae7b5f1d90c9dd1b235093541a781a81e48eda036ce3d079a26", // v1.8.1 to v1.37.2
		"7aaf0dbdb634ae763790e7eccc38898cfd1b96b15502089ee02620a2537c8c41", // v1.38.0 to v3.7.0
	},
	"sdd-explore": {
		"61147ab497a9ec6930b7ac157a28d4e8250dd03c8897e0f4f22d9db592b88bbf", // v1.5.0 to v1.5.4
		"ea955b1c4090d5b3d8c68288263bfb9d4ab5102d7e7b035432d065c1e3d22bf4", // v1.5.5 to v1.8.0
		"ef48771cf44ccdf59d7b65ad2741e5c45b7cd47dce6f33949985e6b38ee96cf5", // v1.8.1 to v1.37.2
		"17352b7ad501a9d78e476c40c0e2b0fa1356d0eb2bc6339d0f5026264bd76df2", // v1.38.0 to v3.7.0
	},
	"sdd-init": {
		"89f1ce4216f10eed8fde37ea444fce145e7a49e8b60e1067ce601cd3eb40b8d0", // v1.5.0 to v1.5.4
		"54f47b3df12e9ea2c9b075c672112d9d0493d7c5b33f319de209183cbf4830fc", // v1.5.5 to v1.8.0
		"e0c892e32df8ea640afea70cf0fd041390233b770247dd58575d88f3f2269634", // v1.8.1 to v1.37.2
		"27811222dec7195167d569eb5adf7f652d845df9743cbdcb7c308e4c2ec5c325", // v1.38.0 to v3.7.0
	},
	"sdd-onboard": {
		"e983b4af9e22af5296e81e024d21e86669ab1fb730c9cb055a660c39998a8fb8", // v1.15.14 to v1.37.2
		"dd7d738f9cca53e869189ccf692063c419fdf40599b1b22b598c55f182415858", // v1.38.0 to v3.7.0
	},
	"sdd-orchestrator": {
		"3beb5a81731cf553f6177c811892c1205e82d40bf3d287598075af2a6c2d3669", // v1.5.0 to v1.24.3
	},
	"sdd-propose": {
		"bc9e737bd760defbac9c99ac23d1128c8013e8d1d19e83d886f4a275876036fd", // v1.5.0 to v1.5.4
		"79d97e35cc97c6a96dbb0fca1da96f42f7229237d867b49e7aecb16570adb165", // v1.5.5 to v1.8.0
		"f7d185412046b37c7fab7a80e09fee13c5c467f8d6b2fe603495fde18eb5fc8d", // v1.8.1 to v1.37.2
		"a33ea90b7db9de887ce8e8183114c6bed9629adf8ecdeb902b83ed3a5a1c794d", // v1.38.0 to v3.7.0
	},
	"sdd-research": {
		"e0595151947a4e2587137c20567cf91db4381ebdf7dfafd9a2f0528d9d71b800", // v2.5.0-rc.1 to v2.9.1
		"1d3bbb12a83b4b4f32c92720502163f94c486f3fba6e8289132496db4595dd3c", // v3.0.0 to v3.7.0
	},
	"sdd-spec": {
		"5ef46c8a7382a04ea0fbf95c8ceceb2874e02457e2c8950446a4fcd669100870", // v1.5.0 to v1.5.4
		"6e3cd0bf2d1542a6eff3ef4e9af70ea45d3664e3c43dbbc0a940c5afc8721488", // v1.5.5 to v1.8.0
		"5d1bbc5c8f629f6c1bf94c1fcd1ef434f51d9ea24b7475568775e891afa296eb", // v1.8.1 to v1.37.2
		"98470c9ea25752783467c358f86ba10114451f6d422484ae316d72ab2634e49e", // v1.38.0 to v3.7.0
	},
	"sdd-tasks": {
		"2e4cce3da3018db44ec241a2e86342d7ad7339fd1d4bdf276932d0023c12faf6", // v1.5.0 to v1.5.4
		"16da9b3cb542d72711fff2dd8cbd12cf14a512720694274a5f8971643c523955", // v1.5.5 to v1.8.0
		"0085af2a87115ce893c6125dc2e55499d7ca06414a19bedc5bee2cc105a464d8", // v1.8.1 to v1.37.2
		"f37f035c64eccdde5ce0ba11df1566b394ea63b526dbaaa53622f17f4f225d3b", // v1.38.0 to v3.7.0
	},
	"sdd-verify": {
		"bfb135464374dd819624cd0a6451f8cacb95485ab16628a0ad0881ae8eff72d7", // v1.5.0 to v1.5.4
		"fb3c3bca2f1d104844230e8db9197c710dcc798e98b9caad731474956f5f6b23", // v1.5.5 to v1.8.0
		"dfd3fee2c6c35ebd1692132a6a345f579c9ce0a4381d4001b2d1360e895c52d9", // v1.8.1 to v1.37.2
		"8c494d846cf943361224a742628e6138bb2580cb85ee2816b4938cb0396684a2", // v1.38.0 to v3.7.0
	},
}

// releasedOpenCodeSDDOrchestratorHeadings lists the heading every released
// orchestrator prompt asset starts with.
var releasedOpenCodeSDDOrchestratorHeadings = map[string][]string{
	"sdd-orchestrator": {
		"# Agent Teams Lite — Lean Orchestrator Instructions",               // v1.3.1 to v1.4.6-beta.1
		"# Agent Teams Lite — Orchestrator Instructions",                    // v1.4.6 to v3.7.0
		"# Agent Teams Lite — Orchestrator Rule for Antigravity",            // v1.4.6 to v1.7.24
		"# Agent Teams Lite — Orchestrator Rule for Codex",                  // v1.7.10 to v1.35.0
		"# Agent Teams Lite — Orchestrator Rule for Gemini",                 // v1.7.10 to v3.7.0
		"# Spec-Driven Development (SDD) — Antigravity",                     // v1.9.0 to v1.10.1
		"# SDD Orchestrator for Cascade (Windsurf) — Hybrid-First",          // v1.9.0 to v1.10.0
		"# Agent Teams Lite — Orchestrator Instructions (Cursor)",           // v1.10.0 to v3.7.0
		"# Agent Teams Lite — Orchestrator Instructions (Windsurf Cascade)", // v1.10.1 to v3.7.0
		"# Agent Teams Lite — Orchestrator Instructions (Antigravity)",      // v1.10.2 to v3.7.0
		"# Agent Teams Lite — Orchestrator Rule for Qwen Code",              // v1.19.0 to v3.7.0
		"# Agent Teams Lite — Orchestrator Instructions (Kiro IDE)",         // v1.20.0 to v3.7.0
		"# Agent Teams Lite — Orchestrator Rule for Kimi",                   // v1.21.0 to v3.7.0
		"# Gentle AI — SDD Orchestrator Instructions",                       // v1.22.0 to v3.7.0
		"# SDD Orchestrator for Codex",                                      // v1.36.0 to v3.7.0
		"# Agent Teams Lite — Orchestrator Rule for Hermes",                 // v1.37.0 to v3.7.0
	},
}

// releasedOpenCodeSDDPromptFiles maps prompts/sdd/<file> to the normalized
// digest of every shared prompt file a release rendered.
var releasedOpenCodeSDDPromptFiles = map[string][]string{
	"sdd-apply.md": {
		"46937f014b68720ba96413e40a9a4691f6c1cf31154fb63fd2442d25b84c81ed", // v1.17.0 to v1.30.6
		"8fd64bb90e0686e965d189b8663054f95e63168835a5712515a5649e06644f79", // v1.30.7 to v1.30.10
		"d41703c2c621ba960cd4f2f03da4811272f351a7768282bd691c4de5cc93dfff", // v1.30.7 to v1.34.1
		"37463c722d90efac7abd6258a7e557fd6d9d65df68fce5c0e83db3ecb6d6bbb6", // v1.31.0 to v1.33.2
		"047be779df3cdcace3661df4d44948e58571cb1ed9d0268988c32595e7b062c0", // v1.34.0 to v1.34.1
		"d2feb29dc902de54b3dd909adf8451acd6d56e64c9d8fd5a6afd43309863bf50", // v1.34.2 to v1.46.0
		"142252762f42236cb7960507bb3fb0f6ce9db0001103bfa899412778ffbbd445", // v1.34.2 to v1.46.0
		"aa7534b390983a5a49281bf53e97c60f6e27bdabb492b9d79531839d0e2039d8", // v1.47.0 to v1.49.0
		"a3e8efad2ab2be508f07f05c91c1c31d9cea7622ec00595905a8cb50fc40f662", // v1.47.0 to v1.49.0
		"10abac870230909bba80e1fb5dcfbbfb7917410b636241c67823972593061470", // v2.0.0 to v2.3.0-rc.2
		"1df3c433d0daaf082163fd5a224686ad3427499635d83e5e8af839addacc30ed", // v2.0.0 to v2.4.0
		"77c46b7028f964593294b966b81ac5c7aee14a5dabe1abfce01aef9d64f559e0", // v2.3.0-rc.3 to v2.4.0
		"928f59790cbc8914ca5388686bc27ea1461b5e9c6c5d6522d66b1cd8123dc89d", // v2.5.0-rc.1
		"998998afc08c28951cce7f2e5d85b4579fd5aed11ba8cbc6eaced76d0ffe0f83", // v2.5.0-rc.1
		"65ebc6710c90e8a85eb804a6b1205cf6b444b071c947437932ad582aa76adbaf", // v2.5.0-rc.2 to v2.5.0-rc.3
		"48e67cf96328d1b90bcaab018eae6cdfa17746e0d31e4c51e6cc12a4cf7459ce", // v2.5.0-rc.2 to v2.5.0-rc.3
		"e198a99c9b61d197a2683ef7541f309dcc711d8a2bc600a0f3b3d5f841db0650", // v2.5.0 to v2.9.1
		"c7696cc4eea988621e23dc30fbb29fce0b8bc097fd6e8d6717692825ecaa7b6c", // v2.5.0 to v2.6.0
		"5a9d0b9d2cdeaacd0fa0de70faef6bde178466b8b80e617bd95d12805ffce6c4", // v2.7.0-rc.1 to v2.9.1
		"9c1e86609a2c691a4288d81adf7c54f8557ec3565c5088c991a06c5e601c7f3a", // v3.0.0 to v3.7.0
		"dfb754328abda66f7c8e3ba4a880e474eff1ad08fa9dc0ebe95f76cd31216eaa", // v3.0.0 to v3.7.0
	},
	"sdd-archive.md": {
		"a8a4d573de8d7fe61caabd8e5d419d23ec582c5bb961de819e0515a1b4a722a5", // v1.17.0 to v1.30.6
		"9b715f0ab33559d81abc417c3e3f4b2f497d858b1e62b3da31c831426fcc5de0", // v1.30.7 to v1.30.10
		"d724f7bc4c8b201c9d2b173ab3f4a51cdfc2d48886438d8c7c879fd9a9dd543a", // v1.31.0 to v1.33.2
		"21c2756b07929631e1c50a6b40dd53f101e370dedeadf1ec605f2c337d29115c", // v1.34.0 to v1.34.1
		"56aeb209a0ed09c5d389e26ffe2e1884a8c136d1d9639a3976c0e5cc6d65f59c", // v1.34.2 to v1.46.0
		"df78bc47639bc017e6c0411fd0ac665c9df70c6f59ad36952046241ed75f669b", // v1.47.0 to v1.49.0
		"b0f6b203eded9f35a9c59a0d51abcdc51eb7900fcbad3cea9a86496741ea05eb", // v2.0.0 to v2.2.0-rc.1
		"3f59ea1b0a523a71da113d10e7c5ea7020f0836325b55b729194414b8fb0f7ea", // v2.2.0 to v2.2.1
		"c291ac9685dc16d7a821da8b277ae22ca860e7a9235cc3ab296db2db2a71b86a", // v2.2.2 to v2.2.4
		"a05ee123abe2ac9185caa9b8a13f6b2086ea0ee7539c12856fdc088856a4a31e", // v2.3.0-rc.1
		"306ad60b68bab6e9293adfde1e062dc9ff0621ce4df08eeeb0a29d519fbfe993", // v2.3.0-rc.2
		"cac28d7a1ad9bb3dbcb34722efe4f6ee7fc557f6aaa1c059a2d93838ecc02d3d", // v2.3.0-rc.3 to v2.4.0-rc.8
		"339670ec2851dbec7680b987e58f471ac37c925997940046fea97aba1c867c0e", // v2.4.0
		"8dc1b56acc6e97c88ddec58a458663b90b61f014085fdc6a1d8eec55ee663052", // v2.5.0-rc.1 to v2.6.0
		"3e081e1bb01169a42dc5e2423185fba5cd834f421b0ac340c1c5c21b243d4954", // v2.7.0-rc.1 to v2.9.1
		"6b0754cee12494490ec49e13dedf53b5e24d0188b7499c9eff1238418809b16b", // v3.0.0 to v3.7.0
	},
	"sdd-design.md": {
		"d8ee33c9d3adfae7b5f1d90c9dd1b235093541a781a81e48eda036ce3d079a26", // v1.17.0 to v1.30.6
		"4081234be86ffd127c62d402fab106d576f9d889ead734aa27863ffce5483806", // v1.30.7 to v1.30.10
		"9c8daf50e3be55ba79915a34236281d2129c0fdec010ceb11fc552e92b66904b", // v1.31.0 to v1.33.2
		"fcb4e81c92b2744432891d2ab75cb00756fa3b588519287dfe47cef9463a3f81", // v1.34.0 to v1.46.0
		"615f31af73165c363229d47679521596a8c5db1ace76c56c7273d484e455239e", // v1.47.0 to v1.49.0
		"957d854191f0b60f624e0592b2759ae8f10f067bf35b76f2a161967b3b2a2e93", // v2.0.0 to v2.3.0-rc.2
		"63548bfbbfd98783001d8073714ff3cd2bf37a269d0f2aeff8476364c8a52830", // v2.3.0-rc.3 to v2.9.1
		"1228f953145a59c2f9755023dc82986aa7cbcffda920cc673e379efe2c8aad8b", // v3.0.0 to v3.7.0
	},
	"sdd-explore.md": {
		"ef48771cf44ccdf59d7b65ad2741e5c45b7cd47dce6f33949985e6b38ee96cf5", // v1.17.0 to v1.30.6
		"2cd06fa08058a4ebb30887569aad2dcbd9dddf396a11293ab21e1cb9dc985a9f", // v1.30.7 to v1.30.10
		"9755e36603ba47c2c986d58b4a2d4af9f9432470ecdc8bf3e865766bedacb2ab", // v1.31.0 to v1.33.2
		"3cd9a1073e3ecce9adbcd8091e2441ddb818efe2ac726b53b38912ccec5307df", // v1.34.0 to v1.49.0
		"05010ebd65fcb084b959eba5d7c12e16a29e53eaa23ed7f2f4a14407ed2b047e", // v2.0.0 to v2.3.0-rc.2
		"6bc9385cbdbaf0da7515fb25967ad5835e85ec57534781e614b773c4fce23b0a", // v2.3.0-rc.3 to v3.7.0
	},
	"sdd-init.md": {
		"e0c892e32df8ea640afea70cf0fd041390233b770247dd58575d88f3f2269634", // v1.17.0 to v1.30.6
		"839cebf653082e3bfdbd1af41dcd0c9d4e113fa1bb31c5a789b4312f231f0e06", // v1.30.7 to v1.30.10
		"761223a9dbe662993fe0a21a97292eaa4e80714c917facbf0fd156b2cfd488e5", // v1.31.0 to v1.33.2
		"7fd14d4dd4e88017073c613821bcdd77e583b82b13fd5138e8b923f9840e85b5", // v1.34.0 to v1.49.0
		"732be7c81c5ba31214df52e097627eaf3cc028c3065e270edb2c9e4409b8cb7c", // v2.0.0 to v2.3.0-rc.2
		"f38e88d79dc1e42e3dcf04596e61921060098025ba49aeb64f6bde24a22e5406", // v2.3.0-rc.3 to v2.4.0
		"6de008c41fa2cdc6ba71dcd5ca8a7f7810c0b566c06f336d86573138e0917701", // v2.5.0-rc.1 to v3.7.0
	},
	"sdd-onboard.md": {
		"e983b4af9e22af5296e81e024d21e86669ab1fb730c9cb055a660c39998a8fb8", // v1.17.0 to v1.30.6
		"b942190314445310e9efecbecedc1067ca50d7926f85ccf0239bfa267112b59d", // v1.30.7 to v1.30.10
		"779356ca8ae34290f4ca35d173cb3a3ce470c3f4d86d363f62526677ae98045d", // v1.31.0 to v1.33.2
		"c7f1e0dffe0c4d46fbe2073d29289ee7342712cb7d14fb65e04c58ac51e4a4ab", // v1.34.0 to v1.49.0
		"5fa7ed85bf8890a02bdb462e2bc11153f4b8382fe862bbf9464ff47182887072", // v2.0.0 to v2.9.1
		"0e15efbe72add5da2bdffa016d97191216a21014dc7b5212d4984dddd85f65cd", // v3.0.0 to v3.7.0
	},
	"sdd-propose.md": {
		"f7d185412046b37c7fab7a80e09fee13c5c467f8d6b2fe603495fde18eb5fc8d", // v1.17.0 to v1.30.6
		"d61eee55edf9122a4b2ebcb397799d230cda37e39d5fb8126cf645f0eb07fc08", // v1.30.7 to v1.30.10
		"a77715a5e32fb29b666a377cd60de3331bb32ffc57ee5890b8aa8be50508ed9f", // v1.31.0 to v1.33.2
		"4d4af70552289fbe3a58b68d5001934d6bb4d532901aa7c03751b1637b2f8172", // v1.34.0
		"e30a9b14d89dbfc90cf418d9af3c02e2032f23efe62df46fa2ee7b0472d25189", // v1.34.1 to v1.49.0
		"9c6c7df8ba26acdc8d24f3e651b3399fe24496ce94acf6c3ef7ad4359d1fb9f4", // v2.0.0 to v2.3.0-rc.2
		"c0fbe5b70204c964a626eb4c129a33e13a49bf7e3eea0773adeed287ab79ffe5", // v2.3.0-rc.3 to v2.4.0
		"8288d6c89d37c88072c37b9a420a931dd6d7662bcf051990276d2b80b188aee0", // v2.5.0-rc.1 to v2.5.0-rc.3
		"3c4a2462669419c94b710b23f177b1fca4b6a61222a61916841ca5ca385ea059", // v2.5.0 to v2.9.1
		"ea8b5d8c5ad3db0d94af32cbd628904224412daa716fb959025c2eb34945dd50", // v3.0.0 to v3.7.0
	},
	"sdd-research.md": {
		"5990433745f219176c54db03d96478c05dcb26754b830b4f95fd233a41a54ff8", // v2.5.0-rc.1 to v2.7.0
		"1c45046e43fe9ebe5d4e9c8443e3f72e5da6fc96e6a4b13c4117eb41e98902ad", // v2.8.0 to v2.9.1
		"69c1b40e08024be0d47b2b37625e81fd4fc4e6dd100e54fbb296b70eafb026ed", // v3.0.0 to v3.7.0
	},
	"sdd-spec.md": {
		"5d1bbc5c8f629f6c1bf94c1fcd1ef434f51d9ea24b7475568775e891afa296eb", // v1.17.0 to v1.30.6
		"3ef1f226e70fe7e326f28283ae50ef5479f74a3c11118f45bd63b8fc7a9e69d6", // v1.30.7 to v1.30.10
		"acc33ae5797af7ef0fc826fa2aa83ffc021f2cd1c193b763c28fa32d9fdc33b6", // v1.31.0 to v1.33.2
		"d47022f050b237c6f71d8314080acde8bc02a8d802cbaa379491e0133cf815e3", // v1.34.0 to v1.34.1
		"f0012d2101e97b1e0ebcb27f74ce0379dcb727dd805f0f2026bb967abf205284", // v1.34.2 to v1.49.0
		"76be211f28d026f7f32a30485bf3f447c2aad1bf9aa1174a1f3ed51ef4282d34", // v2.0.0 to v2.3.0-rc.2
		"cdb91ee1876a0dc92e96b7239fb3f36bc6bf784807dfc1ed4a1d3b207778618f", // v2.3.0-rc.3 to v2.5.0-rc.3
		"cf2980e524146130661e28e1a79a69aff66796cfad134d7e58a5e7d9e7b4b993", // v2.5.0 to v2.9.1
		"1294f4eb31cfd6fde44978acbe10325f7995ccc9e1f8bed4b5a4c591c72043a3", // v3.0.0 to v3.7.0
	},
	"sdd-tasks.md": {
		"0085af2a87115ce893c6125dc2e55499d7ca06414a19bedc5bee2cc105a464d8", // v1.17.0 to v1.30.6
		"c299177395e218a3957468d8adb1339e38ca4b447be893e4530c4fb760c2409f", // v1.30.7 to v1.30.10
		"432ada2eb8aee8f2e8a9a66e8384b111d3bb25749c7dce1951d63f7c58089447", // v1.31.0 to v1.33.2
		"9397f6271d0e5b87b7fbe2f611fdedac8f3cf235833ed4894b6b5ed7a56424f5", // v1.34.0 to v1.46.0
		"a3a75759423a4e2e7c797eecf89bb4235ab5ccd9a78069d2e91cf87b4b0440f5", // v1.47.0 to v1.49.0
		"413a1e9de04367de4fc40a52bd353c195221c5ce574a2693d2a71b96a931b166", // v2.0.0 to v2.3.0-rc.2
		"71bb611eae38382864d04f11ea037737989eb7b88d459f2e4322f77545098561", // v2.3.0-rc.3 to v2.5.0-rc.3
		"85070b06d28f966a3dc48e2f7adc3b46691e9f706fece40512d90ad92b2dd895", // v2.5.0 to v2.9.1
		"0b5d4f801450fec790a6885515055f2767d49c06f89a6a3ff4bcdd9475cf2391", // v3.0.0 to v3.7.0
	},
	"sdd-verify.md": {
		"dfd3fee2c6c35ebd1692132a6a345f579c9ce0a4381d4001b2d1360e895c52d9", // v1.17.0 to v1.30.6
		"b9587ed464418046eca9618515f82a64a416aa7c73cedacd634386809c377927", // v1.30.7 to v1.30.10
		"458f09575c34e68eabb2d323a727d16f4b558d0dabbb7c29b9acc9e348e0b005", // v1.30.7 to v1.33.2
		"3be6eb5fb331a590147d99abcd3e8d73636c06103e7e4f3b4d936891e77e3bd3", // v1.31.0 to v1.33.2
		"3049cc9140b3a8b4fd53188ea9cc902519e9efa1fe5e95fac73aeecab28334b6", // v1.34.0 to v1.34.1
		"916418f8ed17f29b0317003bdf76c28a45a57635e552635d60a58d13db215377", // v1.34.0 to v1.34.1
		"21ae55fa7b8d6a5965ec2844903e3780cf9338f90578deb15c9805993a897d11", // v1.34.2 to v1.46.0
		"9b928510f90f2ba940b0c786681e5e21cba963e73f3f59eda0db3ebfb2af30ed", // v1.34.2 to v1.46.0
		"1a4d5a55173bb452c944b5df2b4ee99cadb438b2974303d474e60f65256cb596", // v1.47.0 to v1.49.0
		"9f0d77d583a67f8441c7841a4e3576fa8aff7f1fcea9167ac1e3c4cb894cfcb8", // v1.47.0 to v1.49.0
		"56b9a8a803ca69b90ec539ec14cde2f44464f1d60d8c0a104f5b7a314c702f11", // v2.0.0 to v2.0.2
		"e7ee7f2ca735a3d519c7d0e7ebd5f1b3495af1db4e216bb210b446f9469bdd50", // v2.0.0 to v2.0.2
		"80a8cf05751ef5a6202dd8d15629710b81cc0a150981a15282583c513029eed0", // v2.1.0 to v2.1.11
		"3ea204f6bbae34ca0edb63f5118cb3140dc46e3221eb6f7472347bc3a50e6663", // v2.1.0 to v2.1.11
		"eca0166331a4759f256376a8a75bdf8a0f2e4086b2d62fe306b85a32c6a8620c", // v2.2.0-rc.1 to v2.3.0-rc.2
		"f9197e5126b21a8dac2e240d69b6d105a7bdd9fc318b76acdb46a441c6a4c7cc", // v2.2.0-rc.1 to v2.4.0-rc.8
		"ee538978e4937ef8a20b87563898ceaa5943f64c069c9ccdfb60106367d36cc5", // v2.3.0-rc.3 to v2.4.0-rc.8
		"e561be39cf87c58e15521b72c9ec9647c8715812bf012f5db1cc7924ac0d1c45", // v2.4.0
		"432e69a3929275bf9939e17da60e3e72478584b569e2b933b06e5cc1d32f425d", // v2.4.0
		"abde94f26688888f65e40a3f7b53c38c4fea455287e80d424d30cc6ea25c1c90", // v2.5.0-rc.1 to v2.5.0-rc.3
		"4f0b82354c3d615991208772449220387c45c1facddc691261bfd633744af6d5", // v2.5.0-rc.1 to v2.6.0
		"660125de09256a935e9bb150b2f54a99c1836944091e20548ace53e16d363129", // v2.5.0 to v2.6.0
		"8bb3713742be080db293b9b2f62f36491b74e1b2c2fee54b27552658e077d0f3", // v2.7.0-rc.1 to v2.9.1
		"a6a8cb816aa15f4227a39b422dfc7ceeec9f8702a3f5e3cea5b690ed9fd87ff0", // v2.7.0-rc.1 to v2.9.1
		"fdf1d100366a01e57c2f79b7d8726e96ee96a2b7f2729259e496ab03f0e40c94", // v3.0.0 to v3.7.0
	},
}
